include:
  - remote: 'https://gitlab.com/pod_security/shared-ci/-/raw/main/security.yml'

image: 'registry.gitlab.com/shardus/dev-container:latest_node18'

before_script:
  - node -v

stages:
  - build
  - appsec

cache:
  paths:
    - node_modules/

format-job:
  stage: build
  script:
    - echo "Running Prettier..."
    - npm run format-check
    - echo "Running Prettier complete."

# Build Job: Compiles the code
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm run compile
    - echo "Compile complete."

# Lint Job: Runs ESLint for code linting
lint-job:
  stage: build
  script:
    - echo "Running ESlint..."
    - npm run lint
    - echo "Running ESlint complete."
