include:
  - remote: 'https://gitlab.com/pod_security/shared-ci/-/raw/main/security.yml'

image: 'registry.gitlab.com/shardus/dev-container:latest_node18'

cache:
  paths:
    - node_modules/

stages:
  - prepare
  - build
  - appsec

# Prepare job: Install Node.js dependencies
prepare-job:
  stage: prepare
  script:
    - node -v
    - apt-get update
    - npm i  #install Node.js dependencies

format-job:
  stage: build
  script:
    - echo "Running Prettier..."
    - npm run format-check
    - echo "Running Prettier complete."

# Build Job: Compiles the code
build-job:
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - echo "Compiling the code..."
    - npm run compile
    - echo "Compile complete."

# Lint Job: Runs ESLint for code linting
lint-job:
  stage: build
  script:
    - echo "Running ESlint..."
    - npm run lint
    - echo "Running ESlint complete."
