[package]
name = "shardus-net"
version = "1.0.2"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.12", features = ["io-util", "net", "rt-multi-thread"] }
neon = { version = "0.9", default-features = false, features = ["napi-6"] }
once_cell = "1.8"